  
version: '3.7'

services:
#api用コンテナ
  api:
    image: 'node:12-alpine'
    volumes:
      - './:/api:cached'
    working_dir: '/api'
    environment:
      HOST: '0.0.0.0'
    ports:
      - '9000:9000'
    command: 'sh -c "npm install && npm run start"'

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
      DATABASE_HOST: localhost
    ports: 
      - "5432:5432"
    volumes:
      - ./migration:/docker-entrypoint-initdb.d